### ISSUE TITLE
Fetch packages immediately following add operation

### ISSUE THREAD

**Issue by shyndman** [shyndman/pubx#9]

**Comment by Vanethos** [comment]
"Fetch packages" as in show the package information in the log OR run `pub get` to get the required dependencies?

If it is to add `pub get` I also suggest adding a `--no-fetch` argument if the user does not want the pub to fetch the new dependencies, either due to low internet bandwith or because a user wants to batch add several dependencies.

**Comment by shyndman** [comment]
pub get, or flutter packages get, depending on context.

Agreed on the flag.

**Comment by Vanethos** [comment]
I'll try todo this!

And @shyndman there's no way for me to assign issues to myself :(
